env: dev
global:
  base_url: https://dummyjson.com
  timeout: 30
  retry_count: 3
  auth:
    username: emilys
    password: emilyspass
dev:
  base_url: https://dummyjson.com
  timeout: 30
  retry_count: 3
  auth:
    username: emilys
    password: emilyspass
staging:
  base_url: https://dummyjson.com
  timeout: 15
  retry_count: 5
  auth:
    username: emilys
    password: emilyspass
prod:
  base_url: https://dummyjson.com
  timeout: 10
  retry_count: 2
  auth:
    username: emilys
    password: emilyspass
